site_name: Minetest Community Docs
site_url:
site_description: An unofficial documentation for Minetest
site_author: Atirut Wattanamongkol

repo_url: https://github.com/WattanaGaming/Minetest-docs

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.tilde
  - pymdownx.superfences