site_name: Unofficial Minetest API Documentation
site_description: An unofficial documentation for Minetest API.
site_author: Atirut Wattanamongkol

repo_url: https://github.com/WattanaGaming/Minetest-docs
theme: readthedocs
