site_name: Minetest Community Docs
site_url:
site_description: An unofficial documentation for Minetest
site_author: Atirut Wattanamongkol

repo_name: atirut-w/minetest-docs
repo_url: https://github.com/atirut-w/minetest-docs

theme:
  name: material
  palette:
    primary: green
    accent: light-green
  features:
    - navigation.instant
    - navigation.top

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes